### ISSUE TITLE
Addition to v1.2.0 TODO: ban 

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#75]
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Simple issue: some players don't want others to _go_ onto their plots. /p ban could solve this

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

## Optional information
#9
