### ISSUE TITLE
v1.0.0 TODO

### ISSUE THREAD

**Issue by jasonwynn10** [jasonwynn10/MyPlot#8]
- [x] Add SubCommands
  - [x] Add claim subcommand
  - [x] Add auto subcommand
  - [x] Add home subcommand
  - [x] Add list subcommand
  - [x] Add info subcommand
  - [x] Add biome subcommand
  - [x] Add biomes subcommand
  - [x] Add clear subcommand
  - [x] Add dispose subcommand
  - [x] Add done subcommand
  - [x] Add deny subcommand
  - [x] Add undeny subcommand
  - [x] Add buy subcommand
  - [x] Add reset subcommand
  - [x] Add middle subcommand
  - [x] Add addhelper subcommand
  - [x] Add removehelper subcommand
  - [x] Add name subcommand
  - [x] Add setowner subcommand
  - [x] Add warp subcommand
- [x] Finish setting up permissions
  - [x] add bypassdeny permission
  - [x] Finish setting max plots with permissions
- [x] Finish DoneMarkTask
- [x] Fix generic reason kick on plot clear
- [x] Finish debugging and test all features on latest server versions with @Aericio

**Comment by jasonwynn10** [comment]
The v1.0.0 Release is right around the corner! all that is left to do is test all the functions and debug errors!
