### ISSUE TITLE
Never Ending TODO List

### ISSUE THREAD

**Issue by jasonwynn10** [jasonwynn10/MyPlot#9]
- [ ] Implement plot buying, selling, and auctioning
- [ ] Add new commands
  - [ ] Add sell command
  - [ ] Add auction command
  - [ ] Add protect command
  - [ ] Add move command
  - [ ] Add expired command
  - [ ] Add addtime command
- [ ] Add new permissions
  - [ ] Add player and admin sell permission
  - [ ] Add player and admin auction permission
  - [ ] Add player and admin protect permission
  - [ ] Add admin move  permission
- [ ] Implement plot expirations
  - [ ] Add resetexpired command
  - [ ] Add admin expired permission
  - [ ] Add admin addtime permission
  - [ ] Add admin resetexpired permission
- [x] Add more Data Providers
  - [x] Add MySQL Provider
  - [x] Add JSON provider
  - [x] Add YAML Provider
- [x] Add custom economy provider API
- [x] Fix MySQL provider
- [x] Event Support
- [x] Add customizable plot generators
- [ ] Finish Debugging (who am I kidding? It never ends)

**Comment by jasonwynn10** [comment]
I might borrow some code from the EconomyS plugins for the expirations

**Comment by Aericio** [comment]
Should I add Travis-CI? To check builds and stuff.

**Comment by jasonwynn10** [comment]
you can if you want

**Comment by jasonwynn10** [comment]
First up to do here will be custom generators so I don't have to solve the user's problems for them...
XD I'm getting lazy!

**Comment by Aericio** [comment]
Can you add this repo to Travis-CI? Then I'll add script.

**Comment by jasonwynn10** [comment]
d454660

**Comment by Aericio** [comment]
actually screw travis, nvm.

**Comment by jasonwynn10** [comment]
... that was a waste

**Comment by jasonwynn10** [comment]
@SalmonGER can you set up Travis-CI for us?

**Comment by Aericio** [comment]
Well, if you already setup travis-ci then i'll add the script then.

**Comment by jasonwynn10** [comment]
most of the needed script is already added, I just need to be able to install pthreads

**Comment by jasonwynn10** [comment]
It Works!!

**Comment by Aericio** [comment]
Well then...

**Comment by jasonwynn10** [comment]
XD sorry, I got bored of waiting...

**Comment by Aericio** [comment]
EssentialsPE's economy support? (It came out a few days ago)

**Comment by Aericio** [comment]
Also, if you want to use releases to upload the phar, make the draft blank. Travis will automatically put the phars there.

**Comment by jasonwynn10** [comment]
I've tried to make travis put the working versions with the releases, but I get an error every time I change the deploy settings, so I will manually add a release for each patch or version bump

**Comment by Aericio** [comment]
I will be testing the commands again.

**Comment by MorpheusTP** [comment]
I will update the german language.

**Comment by MorpheusTP** [comment]
Sorry for my late reply

**Comment by MorpheusTP** [comment]
Just tell me what exacetely and how?

**Comment by Aericio** [comment]
Look up on how to fork a repo and how to make a pull request if you dont know how to do that. Just go to resources and look for deu.ini (or something I forgot) and edit it. Look in English language pack and translate. DO NOT translate commands please. (Ex: /p help cannot be changed, only what is after the command can be changed.)

**Comment by MorpheusTP** [comment]
Okay. In this moment i have to eat I start in 1 hour.

**Comment by MorpheusTP** [comment]
Ok want to start but As I see it already exist? I cant see any difference from the english and the german pack

**Comment by MorpheusTP** [comment]
@Aerico

**Comment by MorpheusTP** [comment]
*@Aericio

**Comment by jasonwynn10** [comment]
The difference is that we added new commands to the english pack, but those weren't added to the german pack. I'll leave you a template file to use.
[template.txt](https://github.com/jasonwynn10/MyPlot/files/659495/template.txt)

**Comment by Aericio** [comment]
If you can't do it, @SalmonGER can translate instead.

**Comment by SalmonGER** [comment]
@Aericio Yeah well accidently committed my changes into the master branch of my fork

**Comment by MorpheusTP** [comment]
Is it already translated by Salmon? If no I can do it now

**Comment by MorpheusTP** [comment]
The Pack was updated!

**Comment by MateiGamingYTB** [comment]
I can translate in Romanian for this plugin, but how?

**Comment by Aericio** [comment]
https://help.github.com/articles/fork-a-repo/
Make an new file called rom.ini. Edit the "langtemplate.ini" file. Be sure to replace "langtemplate" with "rom". After finishing all the translations, [look here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by MateiGamingYTB** [comment]
Ok thanks

**Comment by Driesboy** [comment]
i can do dutch / nederlands

**Comment by Aericio** [comment]
@Driesboy Make a pull request, please.

**Comment by jasonwynn10** [comment]
@Driesboy That would be very helpful to us

**Comment by Driesboy** [comment]
i will start on it soon

**Comment by Callum9966** [comment]
Can there be EconomyAPI support?

**Comment by Aericio** [comment]
>  Add EssentialsPE Economy Support

It is already added.

**Comment by Callum9966** [comment]
I've tried to set it up but it doesn't work.

**Comment by jasonwynn10** [comment]
Please make a seperate issue on this. This one if for our TODO list.

**Comment by Aericio** [comment]
all branches are protected? -_-

**Comment by jasonwynn10** [comment]
@Aericio not all I don't think

**Comment by Aericio** [comment]
Check gitter please. (comment will be deleted).

**Comment by jasonwynn10** [comment]
Customization plot generators was added accidentally but I'll take it 😋

**Comment by Aericio** [comment]
`/p|/plot` command should do something, like redirect itself to `/p help`.
